version: "3.8"
name: textshare
services:
  mongodatabase:
    image: mongo
    container_name: mongodata
    ports:
      - "27070:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

    volumes:
      - textshare-files:/data/db

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: react
    environment:
      VITE_SERVER: http://localhost:5000
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - mongodatabase
    ports:
      - "5000:5000"
    environment:
      DB_URI: mongodb://root:password@mongodatabase
      JWT_SECRET: ITSSUPERSUPERSECRET
      FRONTEND_URL: http://localhost:5173
      PORT: 5000

volumes:
  textshare-files:
    driver: local
